# Generated by Django 4.1.2 on 2023-06-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='profile',
        ),
    ]
