# Generated by Django 4.1.2 on 2023-06-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_guide_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.place'),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
