# Generated by Django 4.1.2 on 2023-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review_reviewimage_guidereview_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
