# Generated by Django 4.1.2 on 2023-06-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_guide_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='total_seats',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.tour'),
        ),
    ]
