# Generated by Django 4.1.2 on 2023-06-22 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tour_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
