# Generated by Django 4.1.2 on 2023-06-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='map_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='app.place'),
        ),
    ]
