# Generated by Django 4.1.2 on 2023-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_place_map_link_alter_tour_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
