# Generated by Django 4.1.2 on 2023-06-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_place_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/tours/'),
        ),
    ]
