# Generated by Django 4.1.2 on 2023-06-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tour_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='place',
            new_name='destination',
        ),
    ]
