# Generated by Django 4.1.2 on 2023-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_guidereview_guide_alter_review_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone1',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone2',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
