# Generated by Django 4.1.2 on 2023-06-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_booking_phone1_booking_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('Failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
