# Generated by Django 4.2.4 on 2023-08-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_product_alter_bookingpayment_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images/products/'),
            preserve_default=False,
        ),
    ]
