# Generated by Django 4.2.4 on 2023-09-13 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rent',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rent',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='app.booking'),
        ),
        migrations.AddField(
            model_name='rent',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rent',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
